name: Publish a release
run-name: ${{ github.actor }} triggered a release upon new tag

on:
  push:
    tags:
      - "ibsim-*.*"

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          ./dist.sh
      - name: Test
        run: |
          test -e ibsim*.tar.gz
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: testing a body for release
          files: |
            ibsim*.tar.gz
